import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Path to the Obsidian vault plugin folder (auto-deploy on build)
// Set PLUGIN_DIR in your .env or shell environment
const VAULT_PLUGIN_DIR = process.env.PLUGIN_DIR || "";

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins,
    ],
    format: "cjs",
    target: "es2022",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    plugins: [
        {
            // Resolve "node:xyz" imports → mark them external (Electron provides them)
            name: "node-builtins",
            setup(build) {
                build.onResolve({ filter: /^node:/ }, (args) => ({
                    path: args.path,
                    external: true,
                }));
            }
        },
        {
            name: "vault-deploy",
            setup(build) {
                build.onEnd(() => {
                    if (existsSync(VAULT_PLUGIN_DIR)) {
                        try {
                            copyFileSync("main.js", `${VAULT_PLUGIN_DIR}/main.js`);
                            copyFileSync("styles.css", `${VAULT_PLUGIN_DIR}/styles.css`);
                            const logoSrc = join(__dirname, "src/assets/logo.png");
                            if (existsSync(logoSrc)) {
                                copyFileSync(logoSrc, `${VAULT_PLUGIN_DIR}/logo.png`);
                            }
                            console.log(`[vault-deploy] → ${VAULT_PLUGIN_DIR}`);
                        } catch (e) {
                            console.warn("[vault-deploy] Copy failed:", e.message);
                        }
                    }
                });
            }
        }
    ],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
